version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: ecommercedb
    volumes:
      - ./postgres:/var/lib/postgresql/data
